export const ROUTES = {
  LOGIN: 'LOGIN',
  HOMESTACK: 'HOMESTACK',
  ADMINSTACK: 'ADMINSTACK',
  CUSTOMERSTACK: 'CUSTOMERSTACK',
  AUTHSTACK: 'AUTHSTACK',
  DASHBOARD: 'DASHBOARD',
  FINANCEREPORT: 'FINANCEREPORT',
  STOCKREPORT: 'STOCKREPORT',
  CYLINDERDELIVERY: 'CYLINDERDELIVERY',
  HANDOVER: 'HANDOVER',
};
